# Generated by Django 5.0.7 on 2024-07-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_queimadas_alter_comentario_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queimadas',
        ),
    ]
